apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment 
  namespace: aplication
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: brunosantos88/aplicationdeveloper:2.0
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
