apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment 
  namespace: aplication
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: brunosantos88/aplicationdeveloper:5.0
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
