apiVersion: v1
kind: Service
metadata:
  name: aplication
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80      # Port on the service
      targetPort: 80  # Port on the pods
      nodePort: 30000  # Port on the nodes
