apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-app
  namespace: jenkins
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/BrunoSantos88/aplication-developer.git'
    path: './jenkins-cluster'
    targetRevision: 'devtest'
project: default
syncPolicy:
    automated:
    prune: true
    selfHeal: true